@host = {{protocol}}://{{hostname}}:{{port}}

###
GET {{host}}/rs/getSymbols/{{locationTags}}

###
GET {{host}}/rs/table_name_not_exist_in_db

###
GET {{host}}/rs/table_for_test

###
GET {{host}}/rs/table_for_test/a1b2c3d4

###
GET {{host}}/rs/table_for_test?name=test&fuzzy=1

###
GET {{host}}/rs/table_for_test?age=>,21

###
POST {{host}}/rs/db_init

###
GET {{host}}/rs/table_for_test?sum=age,ageSum&age=%3C=,20